<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\AnalyticsService\Analytics.Domain\Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\Services\AuthService\Auth.Domain\Auth.Domain.csproj" />
    <ProjectReference Include="..\..\Services\ExpensesService\Expenses.Domain\Expenses.Domain.csproj" />
    <ProjectReference Include="..\..\Services\NotificationsService\Notifications.Domain\Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\Services\PaymentService\Payment.Domain\Payment.Domain.csproj" />
    <ProjectReference Include="..\..\Services\ShoppingService\Shopping.Domain\Shopping.Domain.csproj" />
    <ProjectReference Include="..\..\Services\TaskService\Task.Domain\Task.Domain.csproj" />
    <ProjectReference Include="..\..\Services\UserService\User.Domain\User.Domain.csproj" />
  </ItemGroup>

</Project>
